#!/bin/bash
cat <<EOL > LICENSE
MIT License

Copyright (c) $(date +%Y)

Permission is hereby granted, free of charge, to any person obtaining a copy of this software...
EOL
echo "MIT License created."
